# Generated by Django 4.1.7 on 2023-05-01 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userListName', models.CharField(blank=True, max_length=100, null=True)),
                ('userListPrice', models.FloatField(default=0, null=True)),
                ('countStock', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('data_open', models.DateField(blank=True, default=None, null=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('image', models.ImageField(null=True, upload_to='stock/images/')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonalStockNameUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dbUser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='active.liststock')),
            ],
        ),
        migrations.AddField(
            model_name='liststock',
            name='idStock',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='active.stock'),
        ),
    ]
