# Generated by Django 4.1.7 on 2023-04-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='data_close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='time_close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='time_open',
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
