# Generated by Django 4.1.7 on 2023-05-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liststock',
            name='pers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='active.personalstock'),
        ),
    ]
