# Generated by Django 4.1.7 on 2023-04-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0002_remove_stock_data_close_remove_stock_time_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(null=True, upload_to='stock/images/'),
        ),
    ]
