# Generated by Django 4.1.7 on 2023-05-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0002_liststock_pers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalstock',
            name='dbUser',
        ),
    ]
