# Generated by Django 4.1.7 on 2023-05-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0003_remove_personalstock_dbuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalstock',
            name='countMany',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liststock',
            name='countStock',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
