# Generated by Django 4.1.7 on 2023-05-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0004_personalstock_countmany_alter_liststock_countstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalstock',
            name='totalCountAMD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalstock',
            name='totalCountAMZN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalstock',
            name='totalCountAPLE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalstock',
            name='totalCountMSFT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalstock',
            name='totalCountTSLA',
            field=models.IntegerField(default=0),
        ),
    ]
