# Generated by Django 4.1.7 on 2023-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0007_remove_personalstock_countmany'),
    ]

    operations = [
        migrations.AddField(
            model_name='liststock',
            name='fixPrice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
