# Generated by Django 4.1.7 on 2023-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0008_liststock_fixprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liststock',
            name='fixPrice',
        ),
        migrations.AddField(
            model_name='personalstock',
            name='fixPrice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
