# Generated by Django 4.1.7 on 2023-05-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0011_alter_chatmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
